### ISSUE TITLE
For modelnet10 and modelnet40, how to generate point-image pairs for retrieval?

### ISSUE THREAD

**Issue by zfkarl** [penghu-cs/RONO#1]
Thanks for your contribution. To the best of my knowledge, there exists no image in modelnet10 and modelnet40 datasets. So how do you generate the corresponding images for retrieval?

**Comment by penghu-cs** [comment]
Thank you for your interest in our paper! We followed the setting of the ModelNet10/40 dataset as described in [Cross-Modal-Center-Loss](https://github.com/LongLong-Jing/Cross-Modal-Center-Loss/issues/2), where each 3D object has 180 2D views. We hope this clarifies your question!
