### ISSUE TITLE
About other codes and data

### ISSUE THREAD

**Issue by ganchaofan0000** [penghu-cs/RONO#3]
It is a interesting job. Could you provide other codes and data.

**Comment by Yangl1nFeng** [comment]
Sorry for the delay due to the Chinese New Year and ddl. We have released the code, data, and some checkpoints of ModelNet10/40 in the ModelNet Branch, hoping to help you with your future work. We apologize again for our delay.

**Comment by ganchaofan0000** [comment]
Thanks, Could you provide some detail information about the pre-trained model to extract the feature of points cloud, such as which model, and how much points are used. (1024 or 2048)

**Comment by Yangl1nFeng** [comment]
The pre-trained models for the point-cloud modality, please refer to https://github.com/WangYueFt/dgcnn/tree/master/pytorch/pretrained. Hope this helps.
