### ISSUE TITLE
Confused about Pt_fc and HeadNet

### ISSUE THREAD

**Issue by SL-zZZ** [penghu-cs/RONO#7]
the output dim of Pt_fc is [B,10] but the input dim of HeadNet  must be [B, 256]. Therefore, running open_source_train_mnist.py will generate errors.

**Comment by Yangl1nFeng** [comment]
Hello! Sorry, there is some redundant code here. You can see that self.linear3 in Pt_fc is not actually used, and its output is still 256-dimensional. Hope this helps you!

**Comment by SL-zZZ** [comment]
Thank you for your response！
